### ISSUE TITLE
proper parsing a wad file.

### ISSUE THREAD

**Issue by ThePureCC** [Pupix/lol-wad-parser#19]
how would i do it if i want to parse a wad file with either random or wrong hashes?

`var WadParser = require('lol-wad-parser'),
    wad = new WadParser();

    wad.parse("D:\\new",  function (err, data) {

    });`

i used this piece of code and it gave me error:

`PS D:\NodeJS\node_modules\lol-wad-parser> node 2.js
D:\NodeJS\node_modules\binary-buffer-parser\lib\index.js:42
            throw e;
            ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:733:19)
    at tryReadSync (D:\NodeJS\node_modules\binary-buffer-parser\lib\index.js:39:28)
    at Parser.value (D:\NodeJS\node_modules\binary-buffer-parser\lib\index.js:397:21)
    at Parser.string (D:\NodeJS\node_modules\binary-buffer-parser\lib\index.js:303:31)
    at module.exports (D:\NodeJS\node_modules\lol-wad-parser\lib\parse.js:15:35)
    at FileReader.parse (D:\NodeJS\node_modules\lol-wad-parser\lib\index.js:16:13)
    at Object.apply (D:\NodeJS\node_modules\expandjs\lib\function\apply.js:45:68)
    at WadParser.value (D:\NodeJS\node_modules\lol-file-parser\lib\parser.js:94:24)
    at WadParser.value (D:\NodeJS\node_modules\lol-file-parser\lib\parser.js:61:26)
PS D:\NodeJS\node_modules\lol-wad-parser> node 2.js
D:\NodeJS\node_modules\lol-wad-parser\2.js:4
    wad.parse("D:\\new") {`

**Comment by Pupix** [comment]
`D:\\new` is not a .wad file, it's a directory, that's why it's not working. You gotta pass it a file like so: `"D:\\new\\file.wad".

**Comment by ThePureCC** [comment]
changed it, still didn't work, i feel like i'm missing something very obvious.

would you please provide a whole implementation of the parsing command? Because if I had added a wad file name, where would it be parsing from?

PS D:\NodeJS\node_modules\lol-wad-parser> node 2.js
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\new\asset.wad'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Parser.open (D:\NodeJS\node_modules\binary-buffer-parser\lib\index.js:150:27)
    at WadParser.value (D:\NodeJS\node_modules\lol-file-parser\lib\parser.js:106:34)
    at WadParser.value (D:\NodeJS\node_modules\lol-file-parser\lib\parser.js:60:26)
    at new Promise (D:\NodeJS\node_modules\expandjs\lib\constructors\Promise.js:55:14)
    at WadParser.opt.value [as parse] (D:\NodeJS\node_modules\expandjs\lib\object\defineProperty.js:91:75)
    at Object.<anonymous> (D:\NodeJS\node_modules\lol-wad-parser\2.js:4:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by Pupix** [comment]
```js
var WadParser = require('lol-wad-parser'),
    wad = new WadParser();

    wad.parse('assets.wad', function (err, data) {
        console.log(data);
    });
```

`ENOENT` means the file you are giving it doesn't exist. 😞

**Comment by ThePureCC** [comment]
thank you for the prompt reply, but isn't parser supposed to be "packing" files from where I have extracted and put them back into a wad file? and if so, isn't the command supposed to have a output file name and a input folder name?

**Comment by Pupix** [comment]
No. It analyzes the wad you already have, just like `read` but on a lower level, where you can see every nook and cranny of the file.

![](https://i.imgur.com/rLZxrdc.png)

**Comment by ThePureCC** [comment]
yeah.. my bad, i understood it wrong, i thought it meant "packing". by the way, is packing doable in this case?

**Comment by Pupix** [comment]
Not currently. The files are signed with a private key by Riot Games, editing them would just make the game crash.

**Comment by ThePureCC** [comment]
i understood they're signed by the key, but what if such key validation were bypassed?

**Comment by Pupix** [comment]
This tool still wouldn't pack the files.

To bypass the key check you can use [this](https://github.com/Crauzer/Flow) and to pack WAD files [this](https://github.com/Crauzer/obsidian). There's no guarantee what would happen to your account once you edit the game executable with Flow tho.

**Comment by ThePureCC** [comment]
wow, didn't know these things existed, thank you!
